
version: "3.8"

networks:
    all-inkl-network:
        driver: bridge

services:
    all-inkl-app:
        build:
            context: ./
            dockerfile: Dockerfile
        image: digitalocean.com/php # laravel8-php-fpm-80
        container_name: all-inkl-app
        restart: unless-stopped
        tty: true
        working_dir: /var/www
        volumes:
            - ./src:/var/www
            - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
        networks:
            - all-inkl-network

    all-inkl-mysql:
        image: mysql:latest
        container_name: all-inkl-database
        command: mysqld --default-authentication-plugin=mysql_native_password --skip-mysqlx --lower_case_table_names=1 --sql_mode=""
        restart: unless-stopped
        tty: true
        ports:
            - "3306:3306"
        environment:
            PMA_HOST: all-inkl-database
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: all_inkl_db
            MYSQL_USER: all_inkl_usr
            MYSQL_PASSWORD: all1nklDb
            SERVICE_TAGS: dev
            SERVICE_NAME: all-inkl-database
        security_opt:
            - seccomp:unconfined
        volumes:
            - ./mysql/sql:/docker-entrypoint-initdb.d
            - ./mysql/data:/var/lib/mysql
            - ./mysql/conf:/etc/mysql/conf.d
        networks:
            - all-inkl-network

    all-inkl-nginx:
        image: nginx:1.19.8-alpine
        container_name: all-inkl-nginx
        restart: unless-stopped
        tty: true
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./src:/var/www
            - ./nginx/conf:/etc/nginx/conf.d
        networks:
            - all-inkl-network
